import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Post",
  description: "Generated by Next.js",
};

export default function PostsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Sidebar />
      {children}
    </>
  );
}
