import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function PostsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Sidebar />
      {children}
    </div>
  );
}
